
enableColors: true
enableGlobalCache: false
enableOfflineMode: false
nodeLinker: node-modules

npmScopes:
  zeiss:
    npmAlwaysAuth: true
    npmAuthIdent: "emVpc3M6Rnl0NVdLVzVUTGxmRkpKWDdOUGVuWjg1d2NRVkhqSnp5YnVpVnFjM1hEc3F2eU82N1hSeEpRUUo5OUJKQUNBQUFBQUEyemRuQUFBU0FaRE8zN1cw"
    npmRegistryServer: https://pkgs.dev.azure.com/ZEISSgroup/_packaging/SIP/npm/registry/

yarnPath: .yarn/releases/yarn-4.10.3.cjs